FILE(GLOB dlls ${CMAKE_BINARY_DIR}/../src/*.dll)
MESSAGE(STATUS "Files to copy: ${dlls}. From: ${CMAKE_BINARY_DIR}")
FOREACH(dll ${dlls}) 
	MESSAGE(STATUS "Copying dll runtime file ${dll} to runtime dir ${CMAKE_BINARY_DIR}")
	FILE(COPY ${dll} DESTINATION ${CMAKE_BINARY_DIR})
ENDFOREACH(dll)