#!/bin/sh
#*******************************************************************************
#  Copyright (c) 2016
# 
#  All rights reserved. This program and the accompanying materials
#  are made available under the terms of the Eclipse Public License v1.0
#  and Eclipse Distribution License v1.0 which accompany this distribution. 
# 
#  The Eclipse Public License is available at 
#     http://www.eclipse.org/legal/epl-v10.html
#  and the Eclipse Distribution License is available at 
#    http://www.eclipse.org/org/documents/edl-v10.php.
# 
#  Contributors:
#     Guilherme Maciel Ferreira - initial implementation
#*******************************************************************************/

# Run all tools in the right order
autoreconf --install

# Scan source for missing macros in configure.ac
# autoscan

# Scan "configure.ac"
aclocal --force --install -I m4

# Create "ltmain.sh"
libtoolize --automake

# Create "config.h.in" from "configure.ac"
autoheader

# Create "Makefile.in" from "Makefile.am" and "configure.ac"
automake --add-missing

# Create "configure" from "configure.ac"
autoconf
